os: osx
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py

before_install:
  - brew update;
    brew install python3
    virtualenv -p python3 ~/py-env
    . ~/py-env/bin/activate

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
