os: osx
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/ossl-1/

matrix:
  include:
    - language: generic
      os: osx
      env: TOXENV=py35
    - language: generic
      os: osx
      env: TOXENV=py36

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - ./.travis/upload_coverage.sh
